### ISSUE TITLE
Too many requests to refresh this token

### ISSUE THREAD

**Issue by fulldecent** [NetsoftHoldings/public-api-php-demo#5]
I am trying this approach because it is simple:

POST https://account.hubstaff.com/access_tokens

GET https://api.hubstaff.com/v2/organizations/43979/members

In my cron job every 5 minutes.

---

But now I get:

> Too many requests to refresh this token

This is a dumb and undocumented limitation.

Please update this service to document this at https://developer.hubstaff.com/authentication#access_token and remove the claim that this is a "REST API" or better just remove this limitation.

**Comment by urkle** [comment]
The code in this repository persists the access token and refresh token after the refresh process (the post to access_tokens). 

This must be done and the token used until it expires (either expires_in response from access_tokens OR parse the JWT and use the exp there).  As we do not provide persistent non-expiring tokens in our system as they are, by nature, insecure.

The error is there to deal with users who abuse and refresh before every request which should not be done.

And this is a REST API due to the structure of the endpoints, the authentication system is your standard OAuth 2 with refresh tokens and any other system would have similar rate limiting to prevent abuse.

**Comment by fulldecent** [comment]
The account private key is already on my server. And the access token is also on my server. All accessing my account.

Using my private key to more frequently or less frequently generate an access token **doesn't** make my account any more secure.

But it **does** make it more annoying.

**Comment by urkle** [comment]
We have a policy on our server to limit the amount of times you can refresh a PAT token.   As the access token provided from the refresh lasts 24 hours, thus you should not need to refresh it again for 24 hours.

The code in this demo performs that check by
1) persisting the access token and refresh token
2) checking the expiration within the access token JWT and if it expires within a few minutes it will perform a refresh and then persist the new tokens

Note that this same exact process would be needed for the interactive client-application oauth flow as well.

Now I will work on updating the documentation site to clarify that refreshing an access token is limited. We had some customers who were refreshing it 10s of thousand of times a day when we implemented that rate limit, thus abusing our server resources performing this unneeded refresh.
